using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Atom
{
    public static class Elements
    {
        /// <summary>
        /// Contains ALL the data about elements
        /// </summary>

        private static Element[] elements = new Element[]
        {
            #region Period 1 elements
            new Element("Hydrogen", "H", 
                new Isotope[]{
                    new Isotope(1, true, 99.985f, "Protium"),
                    new Isotope(2, true, 0.015f, "Deuterium"),
                    new Isotope(3, false, 0.0f, "Tritium"),
                    new Isotope(4),
                    new Isotope(5),
                    new Isotope(6),
                    new Isotope(7)
                }),
            new Element("Helium", "He", 
                new Isotope[]{
                    new Isotope(2 , false, 0.0f, "DiProton"),
                    new Isotope(3, true, 0.000137f),
                    new Isotope(4, true, 99.999863f), 
                    new Isotope(5),
                    new Isotope(6),
                    new Isotope(7),
                    new Isotope(8),
                    new Isotope(9),
                    new Isotope(10),
                }),
            #endregion

            #region Period 2 elements
            new Element("Lithium", "Li", 
                new Isotope[]{
                    new Isotope(3),
                    new Isotope(4),
                    new Isotope(5),
                    new Isotope(6, true, 7.59f),
                    new Isotope(7, true, 92.41f),
                    new Isotope(8),
                    new Isotope(9),
                    new Isotope(10),
                    new Isotope(11),
                    new Isotope(12)
                }),
            new Element("Beryllium", "Be",
                new Isotope[]{
                    new Isotope(5),
                    new Isotope(6),
                    new Isotope(7),
                    new Isotope(8),
                    new Isotope(9, true, 100.0f),
                    new Isotope(10),
                    new Isotope(11),
                    new Isotope(12),
                    new Isotope(13),
                    new Isotope(14),
                    new Isotope(15),
                    new Isotope(16)
                }),
            new Element("Boron", "B",
                new Isotope[]{
                    new Isotope(6),
                    new Isotope(7),
                    new Isotope(8),
                    new Isotope(9),
                    new Isotope(10, true, 19.8f),
                    new Isotope(11, true, 80.2f),
                    new Isotope(12),
                    new Isotope(13),
                    new Isotope(14),
                    new Isotope(15),
                    new Isotope(16),
                    new Isotope(17),
                    new Isotope(18),
                }),
            new Element("Carbon", "C",
                new Isotope[]{
                    new Isotope(8),
                    new Isotope(9),
                    new Isotope(10),
                    new Isotope(11),
                    new Isotope(12, true, 98.89f),
                    new Isotope(13, true, 1.11f),
                    new Isotope(14),
                    new Isotope(15),
                    new Isotope(16),
                    new Isotope(17),
                    new Isotope(18),
                    new Isotope(19),
                    new Isotope(20),
                    new Isotope(21),
                    new Isotope(22),
                }),
            new Element("Nitrogen", "N",
                new Isotope[]{
                    new Isotope(10),
                    new Isotope(11),
                    new Isotope(12),
                    new Isotope(13),
                    new Isotope(14, true, 99.634f),
                    new Isotope(15, true, 0.366f),
                    new Isotope(16),
                    new Isotope(17),
                    new Isotope(18),
                    new Isotope(19),
                    new Isotope(20),
                    new Isotope(21),
                    new Isotope(22),
                    new Isotope(23), 
                    new Isotope(24),
                    new Isotope(25)
                }),
            new Element("Oxygen", "O",
                new Isotope[]{
                    new Isotope(12),
                    new Isotope(13),
                    new Isotope(14),
                    new Isotope(15),
                    new Isotope(16, true, 99.762f),
                    new Isotope(17, true, 0.038f),
                    new Isotope(18, true, 0.2f),
                    new Isotope(19),
                    new Isotope(20),
                    new Isotope(21),
                    new Isotope(22),
                    new Isotope(23),
                    new Isotope(24),
                    new Isotope(25),
                    new Isotope(26),
                    new Isotope(27),
                    new Isotope(28)
                }),
            new Element("Fluorine", "F",
                new Isotope[]{
                    new Isotope(14),
                    new Isotope(15),
                    new Isotope(16),
                    new Isotope(17),
                    new Isotope(18),
                    new Isotope(19, true, 100.0f),
                    new Isotope(20),
                    new Isotope(21),
                    new Isotope(22),
                    new Isotope(23),
                    new Isotope(24),
                    new Isotope(25),
                    new Isotope(26),
                    new Isotope(27),
                    new Isotope(28),
                    new Isotope(29),
                    new Isotope(30),
                    new Isotope(31)
                }),
            new Element("Neon", "Ne",
                new Isotope[]{
                    new Isotope(16),
                    new Isotope(17),
                    new Isotope(18),
                    new Isotope(19),
                    new Isotope(20, true, 90.48f),
                    new Isotope(21, true, 0.27f),
                    new Isotope(22, true, 9.25f),
                    new Isotope(23),
                    new Isotope(24),
                    new Isotope(25),
                    new Isotope(26),
                    new Isotope(27),
                    new Isotope(28),
                    new Isotope(29),
                    new Isotope(30),
                    new Isotope(31),
                    new Isotope(32),
                    new Isotope(33),
                    new Isotope(34)
                }),
            #endregion

            #region Period 3 elements
            new Element("Sodium", "Na",
                new Isotope[]{
                    new Isotope(18),
                    new Isotope(19),
                    new Isotope(20),
                    new Isotope(21),
                    new Isotope(22),
                    new Isotope(23, true, 100.0f),
                    new Isotope(24),
                    new Isotope(25),
                    new Isotope(26),
                    new Isotope(27),
                    new Isotope(28),
                    new Isotope(29),
                    new Isotope(30),
                    new Isotope(31),
                    new Isotope(32),
                    new Isotope(33),
                    new Isotope(34),
                    new Isotope(35),
                    new Isotope(36),
                    new Isotope(37)
                }),
            new Element("Magnesium", "Mg",
                new Isotope[]{
                    new Isotope(19),
                    new Isotope(20),
                    new Isotope(21),
                    new Isotope(22),
                    new Isotope(23),
                    new Isotope(24, true, 78.99f),
                    new Isotope(25, true, 10.0f),
                    new Isotope(26, true, 11.01f),
                    new Isotope(27),
                    new Isotope(28),
                    new Isotope(29),
                    new Isotope(30),
                    new Isotope(31),
                    new Isotope(32),
                    new Isotope(33),
                    new Isotope(34),
                    new Isotope(35),
                    new Isotope(36),
                    new Isotope(37),
                    new Isotope(38),
                    new Isotope(39),
                    new Isotope(40)
                }),
            new Element("Aluminium", "Al",
                new Isotope[]{
                    new Isotope(20),
                    new Isotope(21),
                    new Isotope(22),
                    new Isotope(23),
                    new Isotope(24),
                    new Isotope(25),
                    new Isotope(26),
                    new Isotope(27, true, 100.0f),
                    new Isotope(28),
                    new Isotope(29),
                    new Isotope(30),
                    new Isotope(31),
                    new Isotope(32),
                    new Isotope(33),
                    new Isotope(34),
                    new Isotope(35),
                    new Isotope(36),
                    new Isotope(37),
                    new Isotope(38),
                    new Isotope(39),
                    new Isotope(40),
                    new Isotope(41)
                }),
            new Element("Silicon", "Si",
                new Isotope[]{
                    new Isotope(22),
                    new Isotope(23),
                    new Isotope(24),
                    new Isotope(25),
                    new Isotope(26),
                    new Isotope(27),
                    new Isotope(28, true, 92.23f),
                    new Isotope(29, true, 4.683f),
                    new Isotope(30, true, 3.087f),
                    new Isotope(31),
                    new Isotope(32),
                    new Isotope(33),
                    new Isotope(34),
                    new Isotope(35),
                    new Isotope(36),
                    new Isotope(37),
                    new Isotope(38),
                    new Isotope(39),
                    new Isotope(40),
                    new Isotope(41),
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44)
                }),
            new Element("Phosphorus", "P",
                new Isotope[]{
                    new Isotope(24),
                    new Isotope(25),
                    new Isotope(26),
                    new Isotope(27),
                    new Isotope(28),
                    new Isotope(29),
                    new Isotope(30),
                    new Isotope(31, true, 100.0f),
                    new Isotope(32),
                    new Isotope(33),
                    new Isotope(34),
                    new Isotope(35),
                    new Isotope(36),
                    new Isotope(37),
                    new Isotope(38),
                    new Isotope(39),
                    new Isotope(40),
                    new Isotope(41),
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44),
                    new Isotope(45),
                    new Isotope(46),
                }),
            new Element("Sulfur", "S",
                new Isotope[]{
                    new Isotope(26),
                    new Isotope(27),
                    new Isotope(28),
                    new Isotope(29),
                    new Isotope(30),
                    new Isotope(31),
                    new Isotope(32, true, 95.02f),
                    new Isotope(33, true, 0.75f),
                    new Isotope(34, true, 4.21f),
                    new Isotope(35),
                    new Isotope(36, true, 0.02f),
                    new Isotope(37),
                    new Isotope(38),
                    new Isotope(39),
                    new Isotope(40),
                    new Isotope(41),
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44),
                    new Isotope(45),
                    new Isotope(46),
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                }),
            new Element("Chlorine", "Cl",
                new Isotope[]{
                    new Isotope(28),
                    new Isotope(29),
                    new Isotope(30),
                    new Isotope(31),
                    new Isotope(32),
                    new Isotope(33),
                    new Isotope(34),
                    new Isotope(35, true, 75.77f),
                    new Isotope(36),
                    new Isotope(37, true, 24.23f),
                    new Isotope(38),
                    new Isotope(39),
                    new Isotope(40),
                    new Isotope(41),
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44),
                    new Isotope(45),
                    new Isotope(46),
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50),
                    new Isotope(51)
                }),
            new Element("Argon", "Ar",
                new Isotope[]{
                    new Isotope(30),
                    new Isotope(31),
                    new Isotope(32),
                    new Isotope(33),
                    new Isotope(34),
                    new Isotope(35),
                    new Isotope(36, true, 0.3365f),
                    new Isotope(37),
                    new Isotope(38, true, 0.0632f),
                    new Isotope(39),
                    new Isotope(40, true, 99.6003f),
                    new Isotope(41),
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44),
                    new Isotope(45),
                    new Isotope(46),
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50),
                    new Isotope(51),
                    new Isotope(52),
                    new Isotope(53)
                }),
            #endregion
            
            #region Period 4 elements
            new Element("Potassium", "K",
                new Isotope[]{
                    new Isotope(32),
                    new Isotope(33),
                    new Isotope(34),
                    new Isotope(35),
                    new Isotope(36),
                    new Isotope(37),
                    new Isotope(38),
                    new Isotope(39, true, 93.2581f),
                    new Isotope(40, true, 0.0117f),
                    new Isotope(41, true, 6.7302f),
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44),
                    new Isotope(45),
                    new Isotope(46),
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50),
                    new Isotope(51),
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54),
                    new Isotope(55)
                }),
            new Element("Calcium", "Ca",
                new Isotope[]{                    
                    new Isotope(34),
                    new Isotope(35),
                    new Isotope(36),
                    new Isotope(37),
                    new Isotope(38),
                    new Isotope(39),
                    new Isotope(40, true, 96.94f),
                    new Isotope(41),
                    new Isotope(42, true, 0.647f),
                    new Isotope(43, true, 0.135f),
                    new Isotope(44, true, 2.09f),
                    new Isotope(45),
                    new Isotope(46, true, 0.004f),
                    new Isotope(47),
                    new Isotope(48, true, 0.187f),
                    new Isotope(49),
                    new Isotope(50),
                    new Isotope(51),
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54),
                    new Isotope(55),
                    new Isotope(56),
                    new Isotope(57)
                }),
            new Element("Scandium", "Sc",
                new Isotope[]{
                    new Isotope(36),
                    new Isotope(37),
                    new Isotope(38),
                    new Isotope(39),
                    new Isotope(40),
                    new Isotope(41),
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44),
                    new Isotope(45, true, 100f),
                    new Isotope(46),
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50),
                    new Isotope(51),
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54),
                    new Isotope(55),
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58),
                    new Isotope(59),
                    new Isotope(60)
                }),
            new Element("Titanium", "Ti",
                new Isotope[]{
                    new Isotope(38),
                    new Isotope(39),
                    new Isotope(40),
                    new Isotope(41),
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44),
                    new Isotope(45),
                    new Isotope(46, true, 8.25f),
                    new Isotope(47, true, 7.44f),
                    new Isotope(48, true, 73.72f),
                    new Isotope(49, true, 5.41f),
                    new Isotope(50, true, 5.18f),
                    new Isotope(51),
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54),
                    new Isotope(55),
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58),
                    new Isotope(59),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63)
                }),
            new Element("Vanadium", "V",
                new Isotope[]{
                    new Isotope(40),
                    new Isotope(41),
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44),
                    new Isotope(45),
                    new Isotope(46),
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50, true, 0.25f),
                    new Isotope(51, true, 99.75f),
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54),
                    new Isotope(55),
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58),
                    new Isotope(59),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63),
                    new Isotope(64),
                    new Isotope(65)
                }),
            new Element("Chromium", "Cr",
                new Isotope[]{
                    new Isotope(42),
                    new Isotope(43),
                    new Isotope(44),
                    new Isotope(45),
                    new Isotope(46),
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50, true, 4.345f),
                    new Isotope(51),
                    new Isotope(52, true, 83.789f),
                    new Isotope(53, true, 9.501f),
                    new Isotope(54, true, 2.365f),
                    new Isotope(55),
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58),
                    new Isotope(59),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63),
                    new Isotope(64),
                    new Isotope(65),
                    new Isotope(66),
                    new Isotope(67)
                }),
            new Element("Manganese", "Mn",
                new Isotope[]{
                    new Isotope(44),
                    new Isotope(45),
                    new Isotope(46),
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50),
                    new Isotope(51),
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54),
                    new Isotope(55, true, 100.0f),
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58),
                    new Isotope(59),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63),
                    new Isotope(64),
                    new Isotope(65),
                    new Isotope(66),
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69)
                }),
            new Element("Iron", "Fe",
                new Isotope[]{
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50),
                    new Isotope(51),
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54, true, 5.845f),
                    new Isotope(55),
                    new Isotope(56, true, 91.754f),
                    new Isotope(57, true, 2.119f),
                    new Isotope(58, true, 0.282f),
                    new Isotope(59),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63),
                    new Isotope(64),
                    new Isotope(65),
                    new Isotope(66),
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69),
                    new Isotope(70),
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73)
                }),
            new Element("Cobalt", "Co",
                new Isotope[]{
                    new Isotope(47),
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50),
                    new Isotope(51),
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54),
                    new Isotope(55),
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58),
                    new Isotope(59, true, 100.0f),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63),
                    new Isotope(64),
                    new Isotope(65),
                    new Isotope(66),
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69),
                    new Isotope(70),
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75)
                }),
            new Element("Nickel", "Ni",
                new Isotope[]{
                    new Isotope(48),
                    new Isotope(49),
                    new Isotope(50),
                    new Isotope(51),
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54),
                    new Isotope(55),
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58, true, 68.077f),
                    new Isotope(59),
                    new Isotope(60, true, 26.223f),
                    new Isotope(61, true, 1.14f),
                    new Isotope(62, true, 3.634f),
                    new Isotope(63),
                    new Isotope(64),
                    new Isotope(65),
                    new Isotope(66),
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69),
                    new Isotope(70),
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75),
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78)
                }),
            new Element("Copper", "Cu",
                new Isotope[]{
                    new Isotope(52),
                    new Isotope(53),
                    new Isotope(54),
                    new Isotope(55),
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58),
                    new Isotope(59),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63, true, 69.17f),
                    new Isotope(64),
                    new Isotope(65, true, 30.83f),
                    new Isotope(66),
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69),
                    new Isotope(70),
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75),
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78),
                    new Isotope(79),
                    new Isotope(80)
                }),
            new Element("Zinc", "Zn",
                new Isotope[]{
                    new Isotope(54),
                    new Isotope(55),
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58),
                    new Isotope(59),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63),
                    new Isotope(64, true, 48.63f),
                    new Isotope(65),
                    new Isotope(66, true, 27.9f),
                    new Isotope(67, true, 4.1f),
                    new Isotope(68, true, 18.75f),
                    new Isotope(69),
                    new Isotope(70, true, 0.62f),
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75),
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78),
                    new Isotope(79),
                    new Isotope(80),
                    new Isotope(81),
                    new Isotope(82),
                    new Isotope(83)
                }),
            new Element("Gallium", "Ga",
                new Isotope[]{
                    new Isotope(56),
                    new Isotope(57),
                    new Isotope(58),
                    new Isotope(59),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63),
                    new Isotope(64),
                    new Isotope(65),
                    new Isotope(66),
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69, true, 60.108f),
                    new Isotope(70),
                    new Isotope(71, true, 39.892f),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75),
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78),
                    new Isotope(79),
                    new Isotope(80),
                    new Isotope(81),
                    new Isotope(82),
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85),
                    new Isotope(86)
                }),
            new Element("Germanium", "Ge",
                new Isotope[]{
                    new Isotope(58),
                    new Isotope(59),
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63),
                    new Isotope(64),
                    new Isotope(65),
                    new Isotope(66),
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69),
                    new Isotope(70, true, 20.37f),
                    new Isotope(71),
                    new Isotope(72, true, 27.31f),
                    new Isotope(73, true, 7.76f),
                    new Isotope(74, true, 36.73f),
                    new Isotope(75),
                    new Isotope(76, true, 7.83f),
                    new Isotope(77),
                    new Isotope(78),
                    new Isotope(79),
                    new Isotope(80),
                    new Isotope(81),
                    new Isotope(82),
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85),
                    new Isotope(86),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89)
                }),
            new Element("Arsenic", "As",
                new Isotope[]{
                    new Isotope(60),
                    new Isotope(61),
                    new Isotope(62),
                    new Isotope(63),
                    new Isotope(64),
                    new Isotope(65),
                    new Isotope(66),
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69),
                    new Isotope(70),
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75, true, 100.0f),
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78),
                    new Isotope(79),
                    new Isotope(80),
                    new Isotope(81),
                    new Isotope(82),
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85),
                    new Isotope(86),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92)
                }),
            new Element("Selenium", "Se",
                new Isotope[]{
                    new Isotope(65),
                    new Isotope(66),
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69),
                    new Isotope(70),
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74, true, 0.89f),
                    new Isotope(75),
                    new Isotope(76, true, 9.37f),
                    new Isotope(77, true, 7.63f),
                    new Isotope(78, true, 23.77f),
                    new Isotope(79),
                    new Isotope(80, true, 49.61f),
                    new Isotope(81),
                    new Isotope(82, true, 8.73f),
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85),
                    new Isotope(86),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94)
                }),
            new Element("Bromine", "Br",
                new Isotope[]{
                    new Isotope(67),
                    new Isotope(68),
                    new Isotope(69),
                    new Isotope(70),
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75),
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78),
                    new Isotope(79, true, 50.69f),
                    new Isotope(80),
                    new Isotope(81, true, 49.31f),
                    new Isotope(82),
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85),
                    new Isotope(86),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97)
                }),
            new Element("Krypton", "Kr",
                new Isotope[]{
                    new Isotope(69),
                    new Isotope(70),
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75),
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78, true, 0.35f),
                    new Isotope(79),
                    new Isotope(80, true, 2.28f),
                    new Isotope(81),
                    new Isotope(82, true, 11.58f),
                    new Isotope(83, true, 11.49f),
                    new Isotope(84, true, 57.0f),
                    new Isotope(85),
                    new Isotope(86, true, 17.3f),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100)
                }),
            #endregion

            #region Period 5 elements
            new Element("Rubidium", "Rb",
                new Isotope[]{
                    new Isotope(71),
                    new Isotope(72),
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75),
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78),
                    new Isotope(79),
                    new Isotope(80),
                    new Isotope(81),
                    new Isotope(82),
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85, true, 72.17f),
                    new Isotope(86),
                    new Isotope(87, false, 27.83f),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                }),
            new Element("Strontium", "Sr",
                new Isotope[]{
                    new Isotope(73),
                    new Isotope(74),
                    new Isotope(75),
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78),
                    new Isotope(79),
                    new Isotope(80),
                    new Isotope(81),
                    new Isotope(82),
                    new Isotope(83),
                    new Isotope(84, true, 0.56f),
                    new Isotope(85),
                    new Isotope(86, true, 9.86f),
                    new Isotope(87, true, 7.00f),
                    new Isotope(88, true, 82.58f),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105)
                }),
            new Element("Yttrium", "Y",
                new Isotope[]{
                    new Isotope(76),
                    new Isotope(77),
                    new Isotope(78),
                    new Isotope(79),
                    new Isotope(80),
                    new Isotope(81),
                    new Isotope(82),
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85),
                    new Isotope(86),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89, true, 100.0f),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108)
                }),
            new Element("Zirconium ", "Zr",
                new Isotope[]{
                    new Isotope(78),
                    new Isotope(79),
                    new Isotope(80),
                    new Isotope(81),
                    new Isotope(82),
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85),
                    new Isotope(86),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90, true, 51.45f),
                    new Isotope(91, true, 11.22f),
                    new Isotope(92, true, 17.15f),
                    new Isotope(93),
                    new Isotope(94, true, 17.38f),
                    new Isotope(95),
                    new Isotope(96, false, 2.8f),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110)
                }),
            new Element("Niobium", "Nb",
                new Isotope[]{
                    new Isotope(81),
                    new Isotope(82),
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85),
                    new Isotope(86),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93, true, 100.0f),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113)
                }),
            new Element("Molybdenum", "Mo",
                new Isotope[]{
                    new Isotope(83),
                    new Isotope(84),
                    new Isotope(85),
                    new Isotope(86),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92, true, 14.84f),
                    new Isotope(93),
                    new Isotope(94, true, 9.25f),
                    new Isotope(95, true, 15.92f),
                    new Isotope(96, true, 16.68f),
                    new Isotope(97, true, 9.55f),
                    new Isotope(98, true, 24.13f),
                    new Isotope(99),
                    new Isotope(100, false, 9.63f),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115)
                }),
            new Element("Technetium", "Tc",
                new Isotope[]{
                    new Isotope(85),
                    new Isotope(86),
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118)
                }),
            new Element("Ruthenium", "Ru",
                new Isotope[]{
                    new Isotope(87),
                    new Isotope(88),
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96, true, 5.54f),
                    new Isotope(97),
                    new Isotope(98, true, 1.87f),
                    new Isotope(99, true, 12.76f),
                    new Isotope(100, true, 12.6f),
                    new Isotope(101, true, 17.06f),
                    new Isotope(102, true, 31.55f),
                    new Isotope(103),
                    new Isotope(104, true, 18.62f),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120)
                }),
            new Element("Rhodium", "Rh",
                new Isotope[]{
                    new Isotope(89),
                    new Isotope(90),
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103, true, 100.0f),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120),
                    new Isotope(121),
                    new Isotope(122)
                }),
            new Element("Palladium", "Pd",
                new Isotope[]{
                    new Isotope(91),
                    new Isotope(92),
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102, true, 1.02f),
                    new Isotope(103),
                    new Isotope(104, true, 11.14f),
                    new Isotope(105, true, 22.33f),
                    new Isotope(106, true, 27.33f),
                    new Isotope(107),
                    new Isotope(108, true, 26.46f),
                    new Isotope(109),
                    new Isotope(110, true, 11.72f),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120),
                    new Isotope(121),
                    new Isotope(122),
                    new Isotope(123),
                    new Isotope(124)
                }),
            new Element("Silver", "Ag",
                new Isotope[]{
                    new Isotope(93),
                    new Isotope(94),
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107, true, 51.839f),
                    new Isotope(108),
                    new Isotope(109, true, 48.161f),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120),
                    new Isotope(121),
                    new Isotope(122),
                    new Isotope(123),
                    new Isotope(124),
                    new Isotope(125),
                    new Isotope(126),
                    new Isotope(127),
                    new Isotope(128),
                    new Isotope(129),
                    new Isotope(130)
                }),
            new Element("Cadmium", "Cd",
                new Isotope[]{
                    new Isotope(95),
                    new Isotope(96),
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106, true, 1.25f),
                    new Isotope(107),
                    new Isotope(108, false, 0.89f),
                    new Isotope(109),
                    new Isotope(110, true, 12.49f),
                    new Isotope(111, true, 12.8f),
                    new Isotope(112, true, 24.13f),
                    new Isotope(113, false, 12.22f),
                    new Isotope(114, true, 28.73f),
                    new Isotope(115),
                    new Isotope(116, false, 7.49f),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120),
                    new Isotope(121),
                    new Isotope(122),
                    new Isotope(123),
                    new Isotope(124),
                    new Isotope(125),
                    new Isotope(126),
                    new Isotope(127),
                    new Isotope(128),
                    new Isotope(129),
                    new Isotope(130),
                    new Isotope(131),
                    new Isotope(132)
                }),
            new Element("Indium", "In",
                new Isotope[]{
                    new Isotope(97),
                    new Isotope(98),
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113, true, 4.29f),
                    new Isotope(114),
                    new Isotope(115, false, 95.71f),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120),
                    new Isotope(121),
                    new Isotope(122),
                    new Isotope(123),
                    new Isotope(124),
                    new Isotope(125),
                    new Isotope(126),
                    new Isotope(127),
                    new Isotope(128),
                    new Isotope(129),
                    new Isotope(130),
                    new Isotope(131),
                    new Isotope(132),
                    new Isotope(133),
                    new Isotope(134),
                    new Isotope(135)
                }),
            new Element("Tin", "Sn",
                new Isotope[]{
                    new Isotope(99),
                    new Isotope(100),
                    new Isotope(101),
                    new Isotope(102),
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112, true, 0.97f),
                    new Isotope(113),
                    new Isotope(114, true, 0.66f),
                    new Isotope(115, true, 0.34f),
                    new Isotope(116, true, 14.54f),
                    new Isotope(117, true, 7.68f),
                    new Isotope(118, true, 24.22f),
                    new Isotope(119, true, 8.59f),
                    new Isotope(120, true, 32.58f),
                    new Isotope(121),
                    new Isotope(122, true, 4.63f),
                    new Isotope(123),
                    new Isotope(124, true, 5.79f),
                    new Isotope(125),
                    new Isotope(126),
                    new Isotope(127),
                    new Isotope(128),
                    new Isotope(129),
                    new Isotope(130),
                    new Isotope(131),
                    new Isotope(132),
                    new Isotope(133),
                    new Isotope(134),
                    new Isotope(135),
                    new Isotope(136),
                    new Isotope(137)
                }),
            new Element("Antimony", "Sb",
                new Isotope[]{
                    new Isotope(103),
                    new Isotope(104),
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120),
                    new Isotope(121, true, 57.21f),
                    new Isotope(122),
                    new Isotope(123, true, 42.79f),
                    new Isotope(124),
                    new Isotope(125),
                    new Isotope(126),
                    new Isotope(127),
                    new Isotope(128),
                    new Isotope(129),
                    new Isotope(130),
                    new Isotope(131),
                    new Isotope(132),
                    new Isotope(133),
                    new Isotope(134),
                    new Isotope(135),
                    new Isotope(136),
                    new Isotope(137),
                    new Isotope(138),
                    new Isotope(139),
                }),
            new Element("Tellurium", "Te",
                new Isotope[]{
                    new Isotope(105),
                    new Isotope(106),
                    new Isotope(107),
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120, true, 0.09f),
                    new Isotope(121),
                    new Isotope(122, true, 2.55f),
                    new Isotope(123, false, 0.89f),
                    new Isotope(124, true, 4.74f),
                    new Isotope(125, true, 7.07f),
                    new Isotope(126, true, 18.84f),
                    new Isotope(127),
                    new Isotope(128, false, 31.74f),
                    new Isotope(129),
                    new Isotope(130, false, 34.08f),
                    new Isotope(131),
                    new Isotope(132),
                    new Isotope(133),
                    new Isotope(134),
                    new Isotope(135),
                    new Isotope(136),
                    new Isotope(137),
                    new Isotope(138),
                    new Isotope(139),
                    new Isotope(140),
                    new Isotope(141),
                    new Isotope(142)
                }),
            new Element("Iodine", "I",
                new Isotope[]{
                    new Isotope(108),
                    new Isotope(109),
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120),
                    new Isotope(121),
                    new Isotope(122),
                    new Isotope(123),
                    new Isotope(124),
                    new Isotope(125),
                    new Isotope(126),
                    new Isotope(127, true, 100.0f),
                    new Isotope(128),
                    new Isotope(129),
                    new Isotope(130),
                    new Isotope(131),
                    new Isotope(132),
                    new Isotope(133),
                    new Isotope(134),
                    new Isotope(135),
                    new Isotope(136),
                    new Isotope(137),
                    new Isotope(138),
                    new Isotope(139),
                    new Isotope(140),
                    new Isotope(141),
                    new Isotope(142),
                    new Isotope(143),
                    new Isotope(144)
                }),
            new Element("Xenon", "Xe",
                new Isotope[]{ 
                    new Isotope(110),
                    new Isotope(111),
                    new Isotope(112),
                    new Isotope(113),
                    new Isotope(114),
                    new Isotope(115),
                    new Isotope(116),
                    new Isotope(117),
                    new Isotope(118),
                    new Isotope(119),
                    new Isotope(120),
                    new Isotope(121),
                    new Isotope(122),
                    new Isotope(123),
                    new Isotope(124, false, 0.095f),
                    new Isotope(125),
                    new Isotope(126, true, 0.089f),
                    new Isotope(127),
                    new Isotope(128, true, 1.91f),
                    new Isotope(129, true, 26.4f),
                    new Isotope(130, true, 4.071f),
                    new Isotope(131, true, 21.232f),
                    new Isotope(132, true, 26.909f),
                    new Isotope(133),
                    new Isotope(134, false, 10.436f),
                    new Isotope(135),
                    new Isotope(136, false, 8.857f),
                    new Isotope(137),
                    new Isotope(138),
                    new Isotope(139),
                    new Isotope(140),
                    new Isotope(141),
                    new Isotope(142),
                    new Isotope(143),
                    new Isotope(144),
                    new Isotope(145),
                    new Isotope(146),
                    new Isotope(147)
                })
            #endregion
        };

        public static Element GetElement(int protonCount)
        {
            if (protonCount > 0 && protonCount <= elements.Length)
            {
                return elements[protonCount - 1];
            }
            return null;
        }

        public static int NumElements { get { return elements.Length; } }

        public static int[] sblock = new int[] { 2, 2, 2, 2, 2, 2, 2 };
        public static int[] pblock = new int[] { 0, 6, 6, 6, 6, 6, 0 };
        public static int[] dblock = new int[] { 0, 0, 10, 10, 10, 10, 0 };
        public static int[] fblock = new int[] { 0, 0, 0, 14, 14, 0, 0 };

        //Order: 1s, 2s, 2p, 3s, 3p, 4s, 3d, 4p, 5s, 4d, 5p, 6s, 4f, 5d, 6p, 7s, 5f, 6d, 7p

        public static int GetMaxElectrons(int shell, int protonCount)
        {
            int e = sblock[shell];
            e += protonCount > 2 ? pblock[shell] : 0;
            e += protonCount > 18 ? dblock[shell] : 0;
            e += protonCount > 54 ? fblock[shell] : 0;
            return e;
        }

        public static int GetShells(int protonCount)
        {
            if (protonCount == 0)
                return 0;
            if (protonCount <= 2)
                return 1;
            if (protonCount <= 2 + 8)
                return 2;
            if (protonCount <= 2 + 8 + 8)
                return 3;
            if(protonCount <= 2 + 8 + 8 + 18)
                return 4;
            return 5;
        }
    }

    public class Element
    {
        public string Name { get; }
        public string Abbreviation { get; }
        public Isotope[] Isotopes { get; }

        public Element(string name, string abbreviation, Isotope[] isotopes = null)
        {
            Name = name;
            Abbreviation = abbreviation;
            Isotopes = isotopes; 
        }

        public int MaxIsotope { get { return Isotopes[Isotopes.Length - 1].Mass; } }
        public int MinIsotope { get { return Isotopes[0].Mass; } }     

        public Isotope GetIsotope(int mass)
        {
            //make sure there is actually an Isotope
            if (Isotopes != null && mass >= MinIsotope && mass <= MaxIsotope)
            {
                //index = mass - smallest possible mass
                return Isotopes[mass- Isotopes[0].Mass];
            }
            return null;
        }

        /// <summary>
        /// gets the most common isotope of the element
        /// </summary>
        /// <returns></returns>
        public Isotope GetCommon()
        {
            Isotope common = null;
            foreach(Isotope isotope in Isotopes)
            {
                if(isotope.Stable && (common == null || isotope.Abundance > common.Abundance))
                {
                    common = isotope;
                }
            }
            return common;
        }
    }

    public class Isotope
    {
        public int Mass { get; }
        public bool Stable { get; }
        public float Abundance { get; }
        public string FormalName { get; }

        public Isotope(int mass, bool stable = false, float abundance = 0.0f, string formalName = "")
        {
            Mass = mass;
            Stable = stable;
            Abundance = abundance;
            FormalName = formalName;
        }
    }
}

